site_name: learn.jacobkoziej.xyz
site_url: https://learn.jacobkoziej.xyz
repo_url: https://github.com/jacobkoziej/learn
repo_name: jacobkoziej/learn

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: teal
  font:
    text: Fira Sans
    code: Fira Mono
  icon:
    logo: material/book-open-page-variant
  features:
    - instant
    - search
    - tabs

extra:
  social:
    - icon: fontawesome/solid/map-marker-alt
      link: https://jacobkoziej.xyz
      name: jacobkoziej.xyz
    - icon: fontawesome/solid/envelope
      link: mailto:<jacobkoziej@gmail.com>
      name: jacobkoziej@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/jacobkoziej
      name: GitHub
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/koziej.jacob/
      name: Instagram

markdown_extensions:
  - toc:
      permalink: true
