site_name: learn.jacobkoziej.xyz
site_url: https://learn.jacobkoziej.xyz

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: teal
  font:
    text: Fira Sans
    code: Fira Mono
  icon:
    logo: material/book-open-page-variant
  features:
    - instant
    - search
    - tabs

markdown_extensions:
  - toc:
      permalink: true
